import Config

# Configure your database
config :cn23, Cn23.Repo,
  username: "cn23",
  password: "Clo/Zoll Master 3000",
  database: "cn23",
  hostname: "db-02.km8.es",
  show_sensitive_data_on_connection_error: true,
  pool_size: 2

config :cn23, :pow_assent,
  providers: [
    zuubr: [
      client_id: "CLIENT_ID",
      client_secret: "CLIENT_SECRET",
      site: "https://auth.keenmate.com/auth/realms/zuubr",
      # openid
      authorization_params: [scope: "email profile offline_access"],
      strategy: Assent.Strategy.OIDC
    ],
    github: [
      client_id: "CLIENT_ID",
      client_secret: "CLIENT_SECRET",
      strategy: Assent.Strategy.Github
    ]
  ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :cn23, Cn23Web.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "bt3hV+okqI6Ie4hpOKUVb3BDwbzGCQxFC62CqM3MAp0NF9X5fo0w+zuHWXQHNsjo",
  watchers: [
    node: [
      "node_modules/rollup/dist/bin/rollup",
      "--config",
      "--watch",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :cn23, Cn23Web.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/cn23_web/(live|views)/.*(ex)$",
      ~r"lib/cn23_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
